
package com.github.dcal12.web_cache.cache.clientProxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01
 * Generated source version: 2.2
 */
@WebService(name = "FileServer", targetNamespace = "http://server.web_cache.dcal12.github.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface FileServer {


    /**
     * @param arg0
     * @return returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://server.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.cache.clientProxy.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://server.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.cache.clientProxy.DownloadFileResponse")
    @Action(input = "http://server.web_cache.dcal12.github.com/FileServer/downloadFileRequest", output = "http://server.web_cache.dcal12.github.com/FileServer/downloadFileResponse")
    String downloadFile(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @return returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listFiles", targetNamespace = "http://server.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.cache.clientProxy.ListFiles")
    @ResponseWrapper(localName = "listFilesResponse", targetNamespace = "http://server.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.cache.clientProxy.ListFilesResponse")
    @Action(input = "http://server.web_cache.dcal12.github.com/FileServer/listFilesRequest", output = "http://server.web_cache.dcal12.github.com/FileServer/listFilesResponse")
    String[] listFiles();

}
