
package proxySOAP;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AppSOAPService", targetNamespace = "http://app/", wsdlLocation = "http://localhost:8080/app/AppSOAPService?wsdl")
public class AppSOAPService
    extends Service
{

    private final static URL APPSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPSOAPSERVICE_EXCEPTION;
    private final static QName APPSOAPSERVICE_QNAME = new QName("http://app/", "AppSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/app/AppSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPSOAPSERVICE_WSDL_LOCATION = url;
        APPSOAPSERVICE_EXCEPTION = e;
    }

    public AppSOAPService() {
        super(__getWsdlLocation(), APPSOAPSERVICE_QNAME);
    }

    public AppSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPSOAPSERVICE_QNAME, features);
    }

    public AppSOAPService(URL wsdlLocation) {
        super(wsdlLocation, APPSOAPSERVICE_QNAME);
    }

    public AppSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPSOAPSERVICE_QNAME, features);
    }

    public AppSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AppSOAP
     */
    @WebEndpoint(name = "AppSOAPPort")
    public AppSOAP getAppSOAPPort() {
        return super.getPort(new QName("http://app/", "AppSOAPPort"), AppSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppSOAP
     */
    @WebEndpoint(name = "AppSOAPPort")
    public AppSOAP getAppSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://app/", "AppSOAPPort"), AppSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPSOAPSERVICE_EXCEPTION!= null) {
            throw APPSOAPSERVICE_EXCEPTION;
        }
        return APPSOAPSERVICE_WSDL_LOCATION;
    }

}
