
package proxySOAP;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AppSOAP", targetNamespace = "http://app/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AppSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://app/", className = "proxySOAP.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://app/", className = "proxySOAP.GreetResponse")
    @Action(input = "http://app/AppSOAP/greetRequest", output = "http://app/AppSOAP/greetResponse")
    public String greet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
