
package com.github.dcal12.web_cache.client.clientProxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CacheServerAppService", targetNamespace = "http://cache.web_cache.dcal12.github.com/", wsdlLocation = "http://localhost:8090/cache?wsdl")
public class CacheServerAppService
    extends Service
{

    private final static URL CACHESERVERAPPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CACHESERVERAPPSERVICE_EXCEPTION;
    private final static QName CACHESERVERAPPSERVICE_QNAME = new QName("http://cache.web_cache.dcal12.github.com/", "CacheServerAppService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/cache?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CACHESERVERAPPSERVICE_WSDL_LOCATION = url;
        CACHESERVERAPPSERVICE_EXCEPTION = e;
    }

    public CacheServerAppService() {
        super(__getWsdlLocation(), CACHESERVERAPPSERVICE_QNAME);
    }

    public CacheServerAppService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CACHESERVERAPPSERVICE_QNAME, features);
    }

    public CacheServerAppService(URL wsdlLocation) {
        super(wsdlLocation, CACHESERVERAPPSERVICE_QNAME);
    }

    public CacheServerAppService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CACHESERVERAPPSERVICE_QNAME, features);
    }

    public CacheServerAppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CacheServerAppService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CacheServer
     */
    @WebEndpoint(name = "CacheServerAppPort")
    public CacheServer getCacheServerAppPort() {
        return super.getPort(new QName("http://cache.web_cache.dcal12.github.com/", "CacheServerAppPort"), CacheServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CacheServer
     */
    @WebEndpoint(name = "CacheServerAppPort")
    public CacheServer getCacheServerAppPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cache.web_cache.dcal12.github.com/", "CacheServerAppPort"), CacheServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CACHESERVERAPPSERVICE_EXCEPTION!= null) {
            throw CACHESERVERAPPSERVICE_EXCEPTION;
        }
        return CACHESERVERAPPSERVICE_WSDL_LOCATION;
    }

}
