
package com.github.dcal12.web_cache.client.clientProxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CacheServer", targetNamespace = "http://cache.web_cache.dcal12.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CacheServer {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCachedFiles", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.ListCachedFiles")
    @ResponseWrapper(localName = "listCachedFilesResponse", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.ListCachedFilesResponse")
    @Action(input = "http://cache.web_cache.dcal12.github.com/CacheServer/listCachedFilesRequest", output = "http://cache.web_cache.dcal12.github.com/CacheServer/listCachedFilesResponse")
    List<String> listCachedFiles();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listServerFiles", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.ListServerFiles")
    @ResponseWrapper(localName = "listServerFilesResponse", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.ListServerFilesResponse")
    @Action(input = "http://cache.web_cache.dcal12.github.com/CacheServer/listServerFilesRequest", output = "http://cache.web_cache.dcal12.github.com/CacheServer/listServerFilesResponse")
    List<String> listServerFiles();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.DownloadFileResponse")
    @Action(input = "http://cache.web_cache.dcal12.github.com/CacheServer/downloadFileRequest", output = "http://cache.web_cache.dcal12.github.com/CacheServer/downloadFileResponse")
    List<String> downloadFile(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLog", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.GetLog")
    @ResponseWrapper(localName = "getLogResponse", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.GetLogResponse")
    @Action(input = "http://cache.web_cache.dcal12.github.com/CacheServer/getLogRequest", output = "http://cache.web_cache.dcal12.github.com/CacheServer/getLogResponse")
    List<String> getLog();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "clearCache", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.ClearCache")
    @ResponseWrapper(localName = "clearCacheResponse", targetNamespace = "http://cache.web_cache.dcal12.github.com/", className = "com.github.dcal12.web_cache.client.clientProxy.ClearCacheResponse")
    @Action(input = "http://cache.web_cache.dcal12.github.com/CacheServer/clearCacheRequest", output = "http://cache.web_cache.dcal12.github.com/CacheServer/clearCacheResponse")
    void clearCache();

}
